SELECT @@global.time_zone;

SET GLOBAL time_zone = 'America/Sao_Paulo';

CREATE TABLE admins (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(70) NOT NULL,
  password VARCHAR(355) NOT NULL,
  details JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE complements (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id CHAR(36) PRIMARY KEY,
  tumbnail JSON,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  differences JSON,
  note_client DOUBLE,
  categoryId CHAR(36) NOT NULL,
  CONSTRAINT `fk_category_id` FOREIGN KEY (`categoryId`) REFERENCES `categories`(`id`),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE orders (
  id CHAR(36) PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  telefone CHAR(11) NOT NULL,
  endereco JSON,
  mensagem VARCHAR(255) NOT NULL,
  canal VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  segmento VARCHAR(20) NOT NULL,
  produtos JSON,
  pagamento JSON,
  analytics JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
